/**
 * Created by c on 4/21/16.
 */
const CK_COMPONENT_QUERYNESTEDTABLE_UPDATE = 'CK_COMPONENT_QUERYNESTEDTABLE_UPDATE'
const CK_COMPONENT_QUERYNESTEDTABLE_TOGGLEQUERYPANEL = 'CK_COMPONENT_QUERYNESTEDTABLE_TOGGLEQUERYPANEL'

const toggleQueryPanel = () => {
    return {
        type: CK_COMPONENT_QUERYNESTEDTABLE_TOGGLEQUERYPANEL
    }
}

export {
    CK_COMPONENT_QUERYNESTEDTABLE_UPDATE,
    CK_COMPONENT_QUERYNESTEDTABLE_TOGGLEQUERYPANEL,
    toggleQueryPanel,
}