export const FETCH_DATA = 'FETCH_DATA'
export const CLICK_PREV_NEXT_BUTTON = 'CLICK_PREV_NEXT_BUTTON'
export const CLICK_SURE_DATER_BUTTON = 'CLICK_SURE_DATER_BUTTON'
export const IMPORT_BUTTON = 'IMPORT_BUTTON'

