/**
 * Created by janeluck on 4/26/16.
 */
const responseData= {
    "rs": true,
    "data": {
        "total": "53",
        "pages": 3,
        "currentPage": 1,
        "PageRow": 20,
        "rowData": [
            {
                "ID": "28289",
                "Name": "客户3",
                "ShortName": null,
                "Bank": null,
                "BankAccount": null,
                "OwnerID": "霜花",
                "Address": "未设置地址",
                "Lat": "",
                "Lng": "",
                "Phone": null,
                "Descriptions": null,
                "MainProduct": null,
                "Scale": null,
                "AccountLevel": null,
                "Area": null,
                "AccountIndustry": null,
                "WebSite": null,
                "Ww": null,
                "Msnqq": null,
                "Email": null,
                "Customer": null,
                "AccountConnect": null,
                "Beizhu": null,
                "CreatedTime": "2016.02.20 13:57",
                "CreatedType": "1",
                "OptntyCount": null,
                "ContactCount": null,
                "TradingAmount": "0.00",
                "PaymentAmount": "0.00",
                "LeadID": null,
                "LeadCreater": "",
                "LeadOwner": "",
                "LeadSource": ""
            },
            {
                "ID": "28284",
                "Name": "客户1",
                "ShortName": null,
                "Bank": null,
                "BankAccount": null,
                "OwnerID": "霜花",
                "Address": "未设置地址",
                "Lat": "",
                "Lng": "",
                "Phone": null,
                "Descriptions": null,
                "MainProduct": null,
                "Scale": null,
                "AccountLevel": null,
                "Area": null,
                "AccountIndustry": null,
                "WebSite": null,
                "Ww": null,
                "Msnqq": null,
                "Email": null,
                "Customer": null,
                "AccountConnect": null,
                "Beizhu": null,
                "CreatedTime": "2016.02.20 11:31",
                "CreatedType": "1",
                "OptntyCount": null,
                "ContactCount": null,
                "TradingAmount": "0.00",
                "PaymentAmount": "0.00",
                "LeadID": null,
                "LeadCreater": "",
                "LeadOwner": "",
                "LeadSource": ""
            },
            {
                "ID": "28263",
                "Name": "推广和健康",
                "ShortName": null,
                "Bank": null,
                "BankAccount": null,
                "OwnerID": "刘菲菲z",
                "Address": "北清路68号用友园区(用友软件园3号楼1层)",
                "Lat": "40.07578699999999827241",
                "Lng": "116.24269499999999766260",
                "Phone": "",
                "Descriptions": null,
                "MainProduct": null,
                "Scale": "无",
                "AccountLevel": null,
                "Area": null,
                "AccountIndustry": null,
                "WebSite": "",
                "Ww": null,
                "Msnqq": null,
                "Email": null,
                "Customer": null,
                "AccountConnect": null,
                "Beizhu": null,
                "CreatedTime": "2016.02.18 15:08",
                "CreatedType": "1",
                "OptntyCount": null,
                "ContactCount": null,
                "TradingAmount": "0.00",
                "PaymentAmount": "0.00",
                "LeadID": null,
                "LeadCreater": "",
                "LeadOwner": "",
                "LeadSource": ""
            },
            {
                "ID": "28262",
                "Name": "好好换个环境",
                "ShortName": null,
                "Bank": null,
                "BankAccount": null,
                "OwnerID": "刘菲菲z",
                "Address": "北京市海淀区永腾南路",
                "Lat": "40.07438100000000247292",
                "Lng": "116.24234800000000689124",
                "Phone": "",
                "Descriptions": null,
                "MainProduct": null,
                "Scale": "无",
                "AccountLevel": null,
                "Area": null,
                "AccountIndustry": null,
                "WebSite": "",
                "Ww": null,
                "Msnqq": null,
                "Email": null,
                "Customer": null,
                "AccountConnect": null,
                "Beizhu": null,
                "CreatedTime": "2016.02.18 14:54",
                "CreatedType": "1",
                "OptntyCount": null,
                "ContactCount": null,
                "TradingAmount": "0.00",
                "PaymentAmount": "0.00",
                "LeadID": null,
                "LeadCreater": "",
                "LeadOwner": "",
                "LeadSource": ""
            },
            {
                "ID": "28261",
                "Name": "他吞吞吐吐",
                "ShortName": null,
                "Bank": null,
                "BankAccount": null,
                "OwnerID": "刘菲菲z",
                "Address": "东城区",
                "Lat": "39.93477200000000237878",
                "Lng": "116.42277300000000650471",
                "Phone": "",
                "Descriptions": null,
                "MainProduct": null,
                "Scale": "无",
                "AccountLevel": null,
                "Area": null,
                "AccountIndustry": null,
                "WebSite": "",
                "Ww": null,
                "Msnqq": null,
                "Email": null,
                "Customer": null,
                "AccountConnect": null,
                "Beizhu": null,
                "CreatedTime": "2016.02.18 14:53",
                "CreatedType": "1",
                "OptntyCount": null,
                "ContactCount": null,
                "TradingAmount": "0.00",
                "PaymentAmount": "0.00",
                "LeadID": null,
                "LeadCreater": "",
                "LeadOwner": "",
                "LeadSource": ""
            },
            {
                "ID": "28256",
                "Name": "佛祖说",
                "ShortName": null,
                "Bank": null,
                "BankAccount": null,
                "OwnerID": "刘菲菲z",
                "Address": "未设置地址",
                "Lat": "",
                "Lng": "",
                "Phone": "",
                "Descriptions": null,
                "MainProduct": null,
                "Scale": null,
                "AccountLevel": null,
                "Area": null,
                "AccountIndustry": null,
                "WebSite": null,
                "Ww": null,
                "Msnqq": null,
                "Email": null,
                "Customer": null,
                "AccountConnect": null,
                "Beizhu": null,
                "CreatedTime": "2016.02.04 16:26",
                "CreatedType": "1",
                "OptntyCount": null,
                "ContactCount": null,
                "TradingAmount": "0.00",
                "PaymentAmount": "0.00",
                "LeadID": null,
                "LeadCreater": "刘菲菲z",
                "LeadOwner": "刘菲菲z",
                "LeadSource": ""
            },
            {
                "ID": "28255",
                "Name": "某天",
                "ShortName": null,
                "Bank": null,
                "BankAccount": null,
                "OwnerID": "刘菲菲z",
                "Address": "未设置地址",
                "Lat": "",
                "Lng": "",
                "Phone": "",
                "Descriptions": null,
                "MainProduct": null,
                "Scale": null,
                "AccountLevel": null,
                "Area": null,
                "AccountIndustry": null,
                "WebSite": null,
                "Ww": null,
                "Msnqq": null,
                "Email": null,
                "Customer": null,
                "AccountConnect": null,
                "Beizhu": null,
                "CreatedTime": "2016.02.04 16:24",
                "CreatedType": "1",
                "OptntyCount": null,
                "ContactCount": null,
                "TradingAmount": "0.00",
                "PaymentAmount": "0.00",
                "LeadID": null,
                "LeadCreater": "刘菲菲z",
                "LeadOwner": "刘菲菲z",
                "LeadSource": ""
            },
            {
                "ID": "28249",
                "Name": "客户2.2A",
                "ShortName": null,
                "Bank": null,
                "BankAccount": null,
                "OwnerID": "霜花",
                "Address": "未设置地址",
                "Lat": "",
                "Lng": "",
                "Phone": null,
                "Descriptions": null,
                "MainProduct": null,
                "Scale": null,
                "AccountLevel": null,
                "Area": null,
                "AccountIndustry": null,
                "WebSite": null,
                "Ww": null,
                "Msnqq": null,
                "Email": null,
                "Customer": null,
                "AccountConnect": null,
                "Beizhu": null,
                "CreatedTime": "2016.02.02 10:06",
                "CreatedType": "1",
                "OptntyCount": null,
                "ContactCount": null,
                "TradingAmount": "0.00",
                "PaymentAmount": "0.00",
                "LeadID": null,
                "LeadCreater": "",
                "LeadOwner": "",
                "LeadSource": ""
            },
            {
                "ID": "28238",
                "Name": "hh",
                "ShortName": null,
                "Bank": null,
                "BankAccount": null,
                "OwnerID": "刘菲菲z",
                "Address": "北京市",
                "Lat": "39.91101299999999696411",
                "Lng": "116.41355400000000486216",
                "Phone": "",
                "Descriptions": null,
                "MainProduct": null,
                "Scale": "无",
                "AccountLevel": null,
                "Area": null,
                "AccountIndustry": null,
                "WebSite": "",
                "Ww": null,
                "Msnqq": null,
                "Email": null,
                "Customer": null,
                "AccountConnect": null,
                "Beizhu": null,
                "CreatedTime": "2016.02.01 15:46",
                "CreatedType": "1",
                "OptntyCount": null,
                "ContactCount": null,
                "TradingAmount": "0.00",
                "PaymentAmount": "0.00",
                "LeadID": null,
                "LeadCreater": "",
                "LeadOwner": "",
                "LeadSource": ""
            },
            {
                "ID": "28229",
                "Name": "客户AA",
                "ShortName": null,
                "Bank": null,
                "BankAccount": null,
                "OwnerID": "霜花",
                "Address": "未设置地址",
                "Lat": "",
                "Lng": "",
                "Phone": null,
                "Descriptions": null,
                "MainProduct": null,
                "Scale": null,
                "AccountLevel": null,
                "Area": null,
                "AccountIndustry": null,
                "WebSite": null,
                "Ww": null,
                "Msnqq": null,
                "Email": null,
                "Customer": null,
                "AccountConnect": null,
                "Beizhu": null,
                "CreatedTime": "2016.02.01 10:19",
                "CreatedType": "1",
                "OptntyCount": null,
                "ContactCount": null,
                "TradingAmount": "0.00",
                "PaymentAmount": "0.00",
                "LeadID": null,
                "LeadCreater": "",
                "LeadOwner": "",
                "LeadSource": ""
            },
            {
                "ID": "28110",
                "Name": "华亿",
                "ShortName": null,
                "Bank": null,
                "BankAccount": null,
                "OwnerID": "刘菲菲z",
                "Address": "北京市海淀区北清路68号用友软件园中区7号楼",
                "Lat": "40.07562099999999816191",
                "Lng": "116.24176599999999837109",
                "Phone": "15801392556",
                "Descriptions": null,
                "MainProduct": null,
                "Scale": null,
                "AccountLevel": null,
                "Area": null,
                "AccountIndustry": null,
                "WebSite": null,
                "Ww": null,
                "Msnqq": null,
                "Email": null,
                "Customer": null,
                "AccountConnect": null,
                "Beizhu": null,
                "CreatedTime": "2016.01.23 16:25",
                "CreatedType": "1",
                "OptntyCount": null,
                "ContactCount": null,
                "TradingAmount": "0.00",
                "PaymentAmount": "0.00",
                "LeadID": "小诗",
                "LeadCreater": "刘菲菲z",
                "LeadOwner": "刘菲菲z",
                "LeadSource": ""
            },
            {
                "ID": "28029",
                "Name": "demo1452733057.515",
                "ShortName": null,
                "Bank": null,
                "BankAccount": null,
                "OwnerID": "刘菲菲z",
                "Address": "低果2221452733057.515",
                "Lat": "",
                "Lng": "",
                "Phone": null,
                "Descriptions": null,
                "MainProduct": null,
                "Scale": null,
                "AccountLevel": null,
                "Area": null,
                "AccountIndustry": null,
                "WebSite": null,
                "Ww": null,
                "Msnqq": null,
                "Email": null,
                "Customer": null,
                "AccountConnect": null,
                "Beizhu": null,
                "CreatedTime": "2016.01.14 08:57",
                "CreatedType": "1",
                "OptntyCount": null,
                "ContactCount": null,
                "TradingAmount": "0.00",
                "PaymentAmount": "0.00",
                "LeadID": null,
                "LeadCreater": "袁婧",
                "LeadOwner": "袁婧",
                "LeadSource": ""
            },
            {
                "ID": "28028",
                "Name": "demo1452733046.9797",
                "ShortName": null,
                "Bank": null,
                "BankAccount": null,
                "OwnerID": "刘菲菲z",
                "Address": "低果2221452733046.9797",
                "Lat": "",
                "Lng": "",
                "Phone": null,
                "Descriptions": null,
                "MainProduct": null,
                "Scale": null,
                "AccountLevel": null,
                "Area": null,
                "AccountIndustry": null,
                "WebSite": null,
                "Ww": null,
                "Msnqq": null,
                "Email": null,
                "Customer": null,
                "AccountConnect": null,
                "Beizhu": null,
                "CreatedTime": "2016.01.14 08:57",
                "CreatedType": "1",
                "OptntyCount": null,
                "ContactCount": null,
                "TradingAmount": "0.00",
                "PaymentAmount": "0.00",
                "LeadID": null,
                "LeadCreater": "袁婧",
                "LeadOwner": "袁婧",
                "LeadSource": ""
            },
            {
                "ID": "28018",
                "Name": "demo1452650101.3829",
                "ShortName": null,
                "Bank": null,
                "BankAccount": null,
                "OwnerID": "刘菲菲z",
                "Address": "低果2221452650101.3829",
                "Lat": "",
                "Lng": "",
                "Phone": null,
                "Descriptions": null,
                "MainProduct": null,
                "Scale": null,
                "AccountLevel": null,
                "Area": null,
                "AccountIndustry": null,
                "WebSite": null,
                "Ww": null,
                "Msnqq": null,
                "Email": null,
                "Customer": null,
                "AccountConnect": null,
                "Beizhu": null,
                "CreatedTime": "2016.01.13 09:55",
                "CreatedType": "1",
                "OptntyCount": null,
                "ContactCount": null,
                "TradingAmount": "0.00",
                "PaymentAmount": "0.00",
                "LeadID": null,
                "LeadCreater": "袁婧",
                "LeadOwner": "袁婧",
                "LeadSource": ""
            },
            {
                "ID": "28017",
                "Name": "demo1452650088.0048",
                "ShortName": null,
                "Bank": null,
                "BankAccount": null,
                "OwnerID": "刘菲菲z",
                "Address": "低果2221452650088.0049",
                "Lat": "",
                "Lng": "",
                "Phone": null,
                "Descriptions": null,
                "MainProduct": null,
                "Scale": null,
                "AccountLevel": null,
                "Area": null,
                "AccountIndustry": null,
                "WebSite": null,
                "Ww": null,
                "Msnqq": null,
                "Email": null,
                "Customer": null,
                "AccountConnect": null,
                "Beizhu": null,
                "CreatedTime": "2016.01.13 09:54",
                "CreatedType": "1",
                "OptntyCount": null,
                "ContactCount": null,
                "TradingAmount": "0.00",
                "PaymentAmount": "0.00",
                "LeadID": null,
                "LeadCreater": "袁婧",
                "LeadOwner": "袁婧",
                "LeadSource": ""
            },
            {
                "ID": "27974",
                "Name": "demo1452522998.3877",
                "ShortName": null,
                "Bank": null,
                "BankAccount": null,
                "OwnerID": "刘菲菲z",
                "Address": "低果2221452522998.3877",
                "Lat": "",
                "Lng": "",
                "Phone": null,
                "Descriptions": null,
                "MainProduct": null,
                "Scale": null,
                "AccountLevel": null,
                "Area": null,
                "AccountIndustry": null,
                "WebSite": null,
                "Ww": null,
                "Msnqq": null,
                "Email": null,
                "Customer": null,
                "AccountConnect": null,
                "Beizhu": null,
                "CreatedTime": "2016.01.11 22:36",
                "CreatedType": "1",
                "OptntyCount": null,
                "ContactCount": null,
                "TradingAmount": "0.00",
                "PaymentAmount": "0.00",
                "LeadID": null,
                "LeadCreater": "袁婧",
                "LeadOwner": "袁婧",
                "LeadSource": ""
            },
            {
                "ID": "27973",
                "Name": "demo1452522872.6859",
                "ShortName": null,
                "Bank": null,
                "BankAccount": null,
                "OwnerID": "刘菲菲z",
                "Address": "低果2221452522872.6859",
                "Lat": "",
                "Lng": "",
                "Phone": null,
                "Descriptions": null,
                "MainProduct": null,
                "Scale": null,
                "AccountLevel": null,
                "Area": null,
                "AccountIndustry": null,
                "WebSite": null,
                "Ww": null,
                "Msnqq": null,
                "Email": null,
                "Customer": null,
                "AccountConnect": null,
                "Beizhu": null,
                "CreatedTime": "2016.01.11 22:34",
                "CreatedType": "1",
                "OptntyCount": null,
                "ContactCount": null,
                "TradingAmount": "0.00",
                "PaymentAmount": "0.00",
                "LeadID": null,
                "LeadCreater": "袁婧",
                "LeadOwner": "袁婧",
                "LeadSource": ""
            },
            {
                "ID": "27972",
                "Name": "demo1452522814.7698",
                "ShortName": null,
                "Bank": null,
                "BankAccount": null,
                "OwnerID": "刘菲菲z",
                "Address": "低果2221452522814.7698",
                "Lat": "",
                "Lng": "",
                "Phone": null,
                "Descriptions": null,
                "MainProduct": null,
                "Scale": null,
                "AccountLevel": null,
                "Area": null,
                "AccountIndustry": null,
                "WebSite": null,
                "Ww": null,
                "Msnqq": null,
                "Email": null,
                "Customer": null,
                "AccountConnect": null,
                "Beizhu": null,
                "CreatedTime": "2016.01.11 22:33",
                "CreatedType": "1",
                "OptntyCount": null,
                "ContactCount": null,
                "TradingAmount": "0.00",
                "PaymentAmount": "0.00",
                "LeadID": null,
                "LeadCreater": "袁婧",
                "LeadOwner": "袁婧",
                "LeadSource": ""
            },
            {
                "ID": "27971",
                "Name": "demo1452522777.2325",
                "ShortName": null,
                "Bank": null,
                "BankAccount": null,
                "OwnerID": "刘菲菲z",
                "Address": "低果2221452522777.2325",
                "Lat": "",
                "Lng": "",
                "Phone": null,
                "Descriptions": null,
                "MainProduct": null,
                "Scale": null,
                "AccountLevel": null,
                "Area": null,
                "AccountIndustry": null,
                "WebSite": null,
                "Ww": null,
                "Msnqq": null,
                "Email": null,
                "Customer": null,
                "AccountConnect": null,
                "Beizhu": null,
                "CreatedTime": "2016.01.11 22:32",
                "CreatedType": "1",
                "OptntyCount": null,
                "ContactCount": null,
                "TradingAmount": "0.00",
                "PaymentAmount": "0.00",
                "LeadID": null,
                "LeadCreater": "袁婧",
                "LeadOwner": "袁婧",
                "LeadSource": ""
            },
            {
                "ID": "27970",
                "Name": "demo1452522724.417",
                "ShortName": null,
                "Bank": null,
                "BankAccount": null,
                "OwnerID": "刘菲菲z",
                "Address": "低果2221452522724.417",
                "Lat": "",
                "Lng": "",
                "Phone": null,
                "Descriptions": null,
                "MainProduct": null,
                "Scale": null,
                "AccountLevel": null,
                "Area": null,
                "AccountIndustry": null,
                "WebSite": null,
                "Ww": null,
                "Msnqq": null,
                "Email": null,
                "Customer": null,
                "AccountConnect": null,
                "Beizhu": null,
                "CreatedTime": "2016.01.11 22:32",
                "CreatedType": "1",
                "OptntyCount": null,
                "ContactCount": null,
                "TradingAmount": "0.00",
                "PaymentAmount": "0.00",
                "LeadID": null,
                "LeadCreater": "袁婧",
                "LeadOwner": "袁婧",
                "LeadSource": ""
            }
        ]
    }
}

export  {
    responseData
}




